# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetaEgg < Formula
  desc "Awesome Tools to Generate MetaEgg Framework"
  homepage "https://github.com/Jinglever/meta-egg"
  version "3.5.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jinglever/meta-egg/releases/download/v3.5.3/meta-egg-darwin-amd64.zip"
      sha256 "aefd0291a90a4bb14685b6d4f9eb8eb2e6f977ad9ae07871c2bf963038c9a2bb"

      def install
        bin.install "meta-egg"
        generate_completions_from_executable("#{bin}/meta-egg", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jinglever/meta-egg/releases/download/v3.5.3/meta-egg-darwin-arm64.zip"
      sha256 "3dc2d05e9baa8b6b3a7ad82b332cc643426d7cf7890d7d7e87dc19e51ce26ed3"

      def install
        bin.install "meta-egg"
        generate_completions_from_executable("#{bin}/meta-egg", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Jinglever/meta-egg/releases/download/v3.5.3/meta-egg-linux-amd64.zip"
      sha256 "25b6aba75f3a6242f74299c0388a4455181e0494d989369bd2378e56f826c9d6"
      def install
        bin.install "meta-egg"
        generate_completions_from_executable("#{bin}/meta-egg", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Jinglever/meta-egg/releases/download/v3.5.3/meta-egg-linux-arm64.zip"
      sha256 "86d487ffdd52f671b3f15ff34cca68897b49cf706ef2e9479aeca1bdb486ef51"
      def install
        bin.install "meta-egg"
        generate_completions_from_executable("#{bin}/meta-egg", "completion")
      end
    end
  end

  test do
    system "#{bin}/meta-egg" "--version"
  end
end
