# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetaEgg < Formula
  desc "Awesome Tools to Generate MetaEgg Framework"
  homepage "https://github.com/Jinglever/meta-egg"
  version "3.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jinglever/meta-egg/releases/download/v3.8.1/meta-egg-darwin-amd64.zip"
      sha256 "f5555a12040d50528d123cb40b0a812294e9b3b668e4928c4bfdee6630952525"

      def install
        bin.install "meta-egg"
        generate_completions_from_executable("#{bin}/meta-egg", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jinglever/meta-egg/releases/download/v3.8.1/meta-egg-darwin-arm64.zip"
      sha256 "2b7142f30fab4f186d30545bf73ed0ab178b3e1a75aeebd06b23229cd63f3a66"

      def install
        bin.install "meta-egg"
        generate_completions_from_executable("#{bin}/meta-egg", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Jinglever/meta-egg/releases/download/v3.8.1/meta-egg-linux-amd64.zip"
      sha256 "0222380e0ca054c2bc20ed6dd3ac309dbf44b5255fd8cef3265712721d8d9086"
      def install
        bin.install "meta-egg"
        generate_completions_from_executable("#{bin}/meta-egg", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Jinglever/meta-egg/releases/download/v3.8.1/meta-egg-linux-arm64.zip"
      sha256 "290e3fb019c1cbbf88331fb72f873c7390d81ade2d8d7e22cfe616fba69168f0"
      def install
        bin.install "meta-egg"
        generate_completions_from_executable("#{bin}/meta-egg", "completion")
      end
    end
  end

  test do
    system "#{bin}/meta-egg" "--version"
  end
end
